In [ ]:
import numpy as np

In [ ]:
a = np.array([0,0,0,0,0,0,0,0,0,0])

In [ ]:
b = np.array([1,1,1,1,1,1,1,1,1,1])

In [ ]:
c = np.array([5,5,5,5,5,5,5,5,5,5])

In [ ]:
d = np.arange(10,51)
print(d)

In [ ]:
import numpy as np

e = np.arange(10,51)
n=41
for i in range(n):
    if (e[i])%2==0:
      print(e[i])

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [ ]:
import numpy as np
f= np.arange(0,9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
g=np.identity(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
h=np.random.uniform(0,1)
print((h))

0.41487145058250885


In [ ]:
import numpy as np
i=np.array(np.random.normal(0,1,25))
print(i)

[ 0.38449419  0.43474783  0.57713008  1.08302683  0.39595109  0.77882506
  1.27596624  2.58222875  1.09887081 -1.82015592 -0.97221607 -1.03539986
  1.08398259  0.02610305  0.47892066  0.90528856  0.93464871 -0.27993127
 -0.73567807  1.93479069  0.5978523   0.56739706 -1.12634378 -0.4719299
 -0.31799088]


In [ ]:
import numpy as np
j=np.arange(0.01,1.01,0.01)
print(j)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [ ]:
import numpy as np
k=np.linspace(0,1,20)
print(k)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
l = np.arange(1,26).reshape(5,5)
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
l[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
l[3,4]

20

In [ ]:
l[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
l[4]

array([21, 22, 23, 24, 25])

In [ ]:
l[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
l.sum()

325

In [ ]:
l.std()

7.211102550927978

In [ ]:
l.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [ ]:
import numpy as np
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
C=np.dot(A,B)
C

array([[16, 19],
       [26, 31]])

In [ ]:
m=[[1.3,2.5,3.6, np.nan],[2.6,3.3, np.nan,5.5],[2.1,3.2,5.4,6.5]]
n=np.nanmean(m,axis=0)
o=np.where(np.isnan(m))
m[o]=np.take(n,o[1])

TypeError: ignored